### ISSUE TITLE
No sound after installing multirom

### ISSUE THREAD

**Issue by ARTI5T** [vasishath/multirom#15]
After patching boot.img, the speaker does not work (usb-c earphones are working). Using Xiaomi MIX2S.

**Comment by vasishath** [comment]
You may need audio firmware in vendor. Other devices also use it.

**Comment by ARTI5T** [comment]
Does multirom modify the vendor partition? So what happens to the kernel and vendor when injecting boot.img? I flashed the original boot.img and the speaker works again. And injected boot.img affects both internal rom and secondary roms.

**Comment by ARTI5T** [comment]
By the way, is it possible to let every rom have a separate external storage /data/media?

**Comment by ARTI5T** [comment]
In kernel log:
[    1.652650] trampoline: firmware: looking at /etc/firmware/tas2559_uCDSP.bin
[    1.652685] trampoline: firmware: looking at /vendor/firmware/tas2559_uCDSP.bin
[    1.652703] trampoline: firmware: looking at /mrom_enc/vendor/firmware/tas2559_uCDSP.bin
[    1.652723] trampoline: firmware: looking at /firmware/image/tas2559_uCDSP.bin
[    1.652733] trampoline: firmware: could not open 'tas2559_uCDSP.bin': No such file or directory
[    1.652837] tas2559 2-004c: tas2559_fw_ready:
[    1.652843] tas2559 2-004c: tas2559_uCDSP.bin firmware is not loaded.
But the .bin file is in /vendor/firmware.
Originally it is loaded by ueventd but in multirom it says
[   10.772823] ueventd: [libfs_mgr]dt_fstab: Skip disabled entry for partition system

**Comment by vasishath** [comment]
It creates a mini-vendor partition for itself when encryption runs. That
mini-vendor has to contain the firmware. Only then it can load it.
No u can't have separate storage for every rom. Atleast not till now. It
maybe possible however.

**Comment by ARTI5T** [comment]
I didn't include decryption in my build and it always fail when I tried to add the .bin file to the installer.
So how can I put something in ramdisk?

**Comment by vasishath** [comment]
No it won't work if u include the file in zip. This means your device needs
speaker firmware early in the boot so u need to add a firmware directory to
your device tree which include the bin file. And the flag MR_EXTRA_FIRMWARE_DIR
to that.

**Comment by ARTI5T** [comment]
OK. Thank you, problem solved.
