### ISSUE TITLE
Once the boot image is patched, booting to internal rom boots to fastboot

### ISSUE THREAD

**Issue by TAOcroatia** [vasishath/multirom#23]
I'm on Evolution X 4.20 for pocophone, with magisk. The way i get around this issue is to run fastboot boot boot.img on my pc. Is it possible to load the stock boot image from multirom itself, without booting secondary rom?

**Comment by vasishath** [comment]
This is happening on all roms. Google has changed something in the newer release of android 10 which has made it incompatible.
