### ISSUE TITLE
Can't add password to primary after removing it once.

### ISSUE THREAD

**Issue by RockGTR** [vasishath/multirom#5]
I removed the pin in my primary rom (MIUI Globe 8.11.23) then, I added a PIN in secondary rom (LOS 16).
But when I tried to add a pin to my primary after removing the pin in secondary, I couldn't add my fingerprint and PIN.
PS. I have the latest firmware.

**Comment by vasishath** [comment]
You are not supposed to set a PIN on secondary ROM. Its mentioned in the FAQ

**Comment by escomarion** [comment]
so any solution for this thread?or do we need to wipe n clean install a new miui rom?currently on beta miui 8.11.27
