### ISSUE TITLE
Is it able to port multirom to Xiaomi MIX2S?

### ISSUE THREAD

**Issue by ARTI5T** [vasishath/multirom#6]
Since the hardware of Poco F1 and MIX2S are similar, is there any possibility to port to another device?
They are both SDM845 devices.

**Comment by vasishath** [comment]
Yes. You can start porting it. If u need help u can contact me.

**Comment by ARTI5T** [comment]
May I ask you some questions?
Must I use the kernel source code instead of prebuilt kernel?
And should I download full android repo? Since I failed to compile multirom_zip using minimal twrp repo.
And how to solve the encryption problem?
(Please ignore my bad english XD)

**Comment by vasishath** [comment]
U need full Android source. You should use kernel source preferably.

For encryption, I guess mix2s uses file based encryption which multirom doesn't support currently.

**Comment by ARTI5T** [comment]
Thank you.
And according to the original wiki, I need to use a modified TWRP and port kexec_hardboot, is it still necessary now?
BTW, do you know how to disable -Werror globally? It kept warning since I switched to full android source.

**Comment by vasishath** [comment]
No it's not needed anymore.

Globally ? No I don't know about that. I just add -Wno-error to specific project. But it's better to fix what is causing the error.

**Comment by ARTI5T** [comment]
I finally failed to build it for MIX2S. The recovery.img cannot boot. It's a tragedy :(
Could you please try to build it on your build server (if u have time to do so, and if u dont just forget about it :) )? There are already device and vendor repos on github and the codename is polaris. Thanks!

**Comment by ARTI5T** [comment]
Could you make a wiki or a tutorial of the porting? The old one made by Tasssadar might be outdated. I saw enc_blobs in ur device directory which did not appear in the original wiki.
